version: '3.8'

services:
  frontend:
    build:
      context: ./yatdl-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./yatdl-back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/mydatabase"
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongo_data:
